package video

import (
	"bytes"
	"encoding/json"
	"strconv"
)

type playerResponse struct {
	StatusCode int          `json:"status_code"`
	StatusMsg  string       `json:"status_msg"`
	Items      []playerItem `json:"items"`
}

type playerItem struct {
	ID             json.Number      `json:"id"`
	IDStr          string           `json:"id_str"`
	Description    string           `json:"desc"`
	Region         string           `json:"region"`
	AuthorInfo     playerAuthor     `json:"author_info"`
	StatisticsInfo playerStatistics `json:"statistics_info"`
	MusicInfo      playerMusic      `json:"music_info"`
	VideoInfo      playerVideoInfo  `json:"video_info"`
}

type playerAuthor struct {
	AvatarURLs []string `json:"avatar_url_list"`
	Nickname   string   `json:"nickname"`
	SecretID   string   `json:"secret_id"`
	UniqueID   string   `json:"unique_id"`
}

type playerStatistics struct {
	CommentCount int64 `json:"comment_count"`
	DiggCount    int64 `json:"digg_count"`
	ShareCount   int64 `json:"share_count"`
}

type playerMusic struct {
	IDStr  string `json:"id_str"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

type playerVideoInfo struct {
	URI         string          `json:"uri"`
	URLList     []string        `json:"url_list"`
	Meta        playerVideoMeta `json:"meta"`
	Cover       playerURLList   `json:"cover"`
	OriginCover playerURLList   `json:"origin_cover"`
	Profiles    []playerProfile `json:"profiles"`
	CLAInfo     playerCLAInfo   `json:"cla_info"`
}

type playerVideoMeta struct {
	Bitrate  int64  `json:"bitrate"`
	Duration int    `json:"duration"`
	Format   string `json:"format"`
	Height   int    `json:"height"`
	Width    int    `json:"width"`
}

type playerURLList struct {
	URLList []string `json:"url_list"`
}

type playerProfile struct {
	Bitrate   int64             `json:"bitrate"`
	CodecType string            `json:"codec_type"`
	FPS       int               `json:"fps"`
	GearName  string            `json:"gear_name"`
	PlayAddr  playerPlayAddress `json:"play_addr"`
}

type playerPlayAddress struct {
	DataSize int64    `json:"data_size"`
	Height   int      `json:"height"`
	URI      string   `json:"uri"`
	URLKey   string   `json:"url_key"`
	URLList  []string `json:"url_list"`
	Width    int      `json:"width"`
}

type playerCLAInfo struct {
	CaptionInfos []playerCaption `json:"caption_infos"`
}

type playerCaption struct {
	CaptionFormat     string   `json:"caption_format"`
	Expire            int64    `json:"expire"`
	IsAutoGenerated   bool     `json:"is_auto_generated"`
	IsOriginalCaption bool     `json:"is_original_caption"`
	Language          string   `json:"lang"`
	URL               string   `json:"url"`
	URLList           []string `json:"url_list"`
}

type frontityState struct {
	Source struct {
		Data map[string]embedPageData `json:"data"`
	} `json:"source"`
}

type embedPageData struct {
	VideoData embedVideoData `json:"videoData"`
	Code      int            `json:"code"`
	IsError   bool           `json:"isError"`
}

type embedVideoData struct {
	ItemInfos         embedItem             `json:"itemInfos"`
	AuthorInfos       embedAuthor           `json:"authorInfos"`
	AuthorStats       embedAuthorStatistics `json:"authorStats"`
	MusicInfos        embedMusic            `json:"musicInfos"`
	ChallengeInfoList []embedChallenge      `json:"challengeInfoList"`
}

type embedItem struct {
	ID              string     `json:"id"`
	Text            string     `json:"text"`
	CreateTime      string     `json:"createTime"`
	AuthorID        string     `json:"authorId"`
	Covers          []string   `json:"covers"`
	CoversOrigin    []string   `json:"coversOrigin"`
	CoversDynamic   []string   `json:"coversDynamic"`
	DiggCount       int64      `json:"diggCount"`
	ShareCount      int64      `json:"shareCount"`
	PlayCount       int64      `json:"playCount"`
	CommentCount    int64      `json:"commentCount"`
	LocationCreated string     `json:"locationCreated"`
	Video           embedVideo `json:"video"`
}

type embedVideo struct {
	URLs      []string       `json:"urls"`
	VideoMeta embedVideoMeta `json:"videoMeta"`
}

type embedVideoMeta struct {
	Width    int `json:"width"`
	Height   int `json:"height"`
	Duration int `json:"duration"`
}

type embedAuthor struct {
	SecUID       string   `json:"secUid"`
	UserID       string   `json:"userId"`
	UniqueID     string   `json:"uniqueId"`
	Nickname     string   `json:"nickName"`
	Signature    string   `json:"signature"`
	Verified     bool     `json:"verified"`
	Covers       []string `json:"covers"`
	CoversMedium []string `json:"coversMedium"`
	CoversLarger []string `json:"coversLarger"`
}

type embedAuthorStatistics struct {
	FollowingCount flexibleInt64 `json:"followingCount"`
	FollowerCount  flexibleInt64 `json:"followerCount"`
	HeartCount     flexibleInt64 `json:"heartCount"`
	VideoCount     flexibleInt64 `json:"videoCount"`
	DiggCount      flexibleInt64 `json:"diggCount"`
}

type embedMusic struct {
	MusicID      string   `json:"musicId"`
	MusicName    string   `json:"musicName"`
	AuthorName   string   `json:"authorName"`
	PlayURL      []string `json:"playUrl"`
	Covers       []string `json:"covers"`
	CoversMedium []string `json:"coversMedium"`
	CoversLarger []string `json:"coversLarger"`
}

type embedChallenge struct {
	ChallengeID   string `json:"challengeId"`
	ChallengeName string `json:"challengeName"`
	Text          string `json:"text"`
	IsCommerce    bool   `json:"isCommerce"`
}

type flexibleInt64 int64

func (value *flexibleInt64) UnmarshalJSON(data []byte) error {
	data = bytes.TrimSpace(data)
	if bytes.Equal(data, []byte("null")) || len(data) == 0 {
		*value = 0
		return nil
	}
	if data[0] == '"' {
		var text string
		if err := json.Unmarshal(data, &text); err != nil {
			return err
		}
		number, err := strconv.ParseInt(text, 10, 64)
		if err != nil {
			return err
		}
		*value = flexibleInt64(number)
		return nil
	}
	number, err := strconv.ParseInt(string(data), 10, 64)
	if err != nil {
		return err
	}
	*value = flexibleInt64(number)
	return nil
}
