// Package video resolves TikTok video metadata and downloadable media.
package video

import "time"

// DefaultUserAgent follows TikTok's mobile web path, which exposes the complete
// server-rendered video state more consistently than its desktop CSR fallback.
const DefaultUserAgent = "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) " +
	"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36"

// ClientOptions configures the HTTP session used to crawl TikTok videos.
type ClientOptions struct {
	Cookie    string
	UserAgent string
}

// Result contains normalized video metadata and every downloadable media variant.
type Result struct {
	InputURL  string    `json:"input_url"`
	FinalURL  string    `json:"final_url"`
	Sources   []string  `json:"sources"`
	FetchedAt time.Time `json:"fetched_at"`
	Warnings  []string  `json:"warnings,omitempty"`
	Video     Video     `json:"video"`
	Media     []Media   `json:"media"`
}

// Video describes a TikTok post and its related public metadata.
type Video struct {
	ID          string     `json:"id"`
	Description string     `json:"description"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Region      string     `json:"region,omitempty"`
	Duration    int        `json:"duration_seconds"`
	Width       int        `json:"width"`
	Height      int        `json:"height"`
	Author      Author     `json:"author"`
	Statistics  Statistics `json:"statistics"`
	Music       Music      `json:"music"`
	Covers      Covers     `json:"covers"`
	Hashtags    []Hashtag  `json:"hashtags,omitempty"`
	Captions    []Caption  `json:"captions,omitempty"`
}

// Author describes the account that published the video.
type Author struct {
	ID         string           `json:"id,omitempty"`
	SecUID     string           `json:"sec_uid,omitempty"`
	UniqueID   string           `json:"unique_id"`
	Nickname   string           `json:"nickname"`
	Signature  string           `json:"signature,omitempty"`
	Verified   bool             `json:"verified"`
	AvatarURLs []string         `json:"avatar_urls,omitempty"`
	Statistics AuthorStatistics `json:"statistics"`
}

// AuthorStatistics contains public account counters returned by the embed page.
type AuthorStatistics struct {
	FollowingCount int64 `json:"following_count"`
	FollowerCount  int64 `json:"follower_count"`
	HeartCount     int64 `json:"heart_count"`
	VideoCount     int64 `json:"video_count"`
	DiggCount      int64 `json:"digg_count"`
}

// Statistics contains public engagement counters for the video.
type Statistics struct {
	PlayCount    int64 `json:"play_count"`
	LikeCount    int64 `json:"like_count"`
	CommentCount int64 `json:"comment_count"`
	ShareCount   int64 `json:"share_count"`
}

// Music describes the audio attached to the video.
type Music struct {
	ID           string   `json:"id,omitempty"`
	Title        string   `json:"title,omitempty"`
	Author       string   `json:"author,omitempty"`
	PlaybackURLs []string `json:"playback_urls,omitempty"`
	CoverURLs    []string `json:"cover_urls,omitempty"`
}

// Covers contains the static and original video cover URLs.
type Covers struct {
	Default  []string `json:"default,omitempty"`
	Original []string `json:"original,omitempty"`
	Dynamic  []string `json:"dynamic,omitempty"`
}

// Hashtag describes one challenge or hashtag attached to the post.
type Hashtag struct {
	ID         string `json:"id,omitempty"`
	Name       string `json:"name"`
	Text       string `json:"text,omitempty"`
	IsCommerce bool   `json:"is_commerce"`
}

// Caption describes one subtitle track exposed by TikTok's player.
type Caption struct {
	Language      string     `json:"language"`
	Format        string     `json:"format"`
	URL           string     `json:"url"`
	AutoGenerated bool       `json:"auto_generated"`
	Original      bool       `json:"original"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
}

// Media is one downloadable encoding of a TikTok video.
type Media struct {
	Kind        string     `json:"kind"`
	Watermarked bool       `json:"watermarked"`
	Codec       string     `json:"codec"`
	Format      string     `json:"format"`
	Quality     string     `json:"quality"`
	GearName    string     `json:"gear_name,omitempty"`
	Width       int        `json:"width"`
	Height      int        `json:"height"`
	FPS         int        `json:"fps,omitempty"`
	Bitrate     int64      `json:"bitrate,omitempty"`
	Size        int64      `json:"size,omitempty"`
	URI         string     `json:"uri,omitempty"`
	URL         string     `json:"url"`
	BackupURLs  []string   `json:"backup_urls,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
}

// SelectOptions filters media variants before the highest-resolution match is selected.
type SelectOptions struct {
	Quality     string
	Watermarked bool
}

// DownloadOptions controls where and how a media file is saved.
type DownloadOptions struct {
	OutputPath string
	Referer    string
	Progress   func(DownloadProgress)
}

// DownloadProgress reports the current number of downloaded bytes and the expected total.
type DownloadProgress struct {
	DownloadedBytes int64
	TotalBytes      int64
}

// DownloadResult describes a completed media download.
type DownloadResult struct {
	Path        string `json:"path"`
	Bytes       int64  `json:"bytes"`
	ContentType string `json:"content_type"`
	SourceURL   string `json:"source_url"`
}
